name: Create Pull Request

on:
  push:
    branches-ignore:
      - main

env:
  BASE_BRANCH: main
  REVIEWER: mami0tsu

jobs:
  create-pull-request:
    if: ${{ !github.event.created }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-reuest: write
    steps:
      - name: Checkout
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Check
        id: check
        run: echo "count=$(gh pr list -B ${{ env.BASE_BRANCH }} -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: ${{ steps.check.outputs.count == '' }}
        run: gh pr create --fill -B ${{ env.BASE_BRANCH }} -r ${{ env.REVIEWER }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
