name: terraform

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**/*.tf'

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: echo pwd
        run: pwd
      - name: Setup terraform
        # v2.0.3
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
      - name: Format
        id: format
        run: terraform fmt -check
      - name: Init
        id: init
        run: terraform init
      - name: Plan
        id: plan
        run: terraform plan
        continue-on-error: true
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
